-
  name: Play1
  become: yes 
  hosts: agent1
  vars:
    packages:
      - mysql-server
      - apache2
      - mongodb
      - nodejs
  tasks: 
    -
      name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
