-
  name: Play1
  hosts: agent1
  become: yes
  tasks:
    -
      name: add several users
      user:
        name: "{{ item }}"
        state: present
        group: docker
      with_items:
        - testuser1
        - testuser2
        - testuser3


