-
  name: Play1
  become: yes
  hosts: agent1
  vars:
    country_name: INDIA
    state_name: JHARKHAND
    city_name: RANCHI
  tasks:
    -
      name: Print my country name
      command: echo "My country name is {{ country_name }}"

    -
      name: Print my state name
      command: echo "My state name is {{ state_name }}"

    -
      name: Print my city name
      command: echo "My city name is {{ city_name }}"
